### PR TITLE
rebase from libp2p

### PR DESCRIPTION
**Pull request by chaitanyaprem**

### CODE REVIEW

**Review by richard-ramos — APPROVED** [review]

**Comment by chaitanyaprem** [comment]
@richard-ramos not sure why the `TestGossipsubConnTagMessageDeliveries` test is failing in ubuntu. I tried to run it again but still fails in CI.

I have run it locally in my mac and it is fine. If you have an ubuntu machine, can you try running it locally to confirm if it passes?

**Comment by richard-ramos** [comment]
Taking a look at this

**Comment by richard-ramos** [comment]
Maybe it's flaky? If i run it with
```
go test -run TestGossipsubConnTagMessageDeliveries -count 100 --failfast ./...
```
I get
```
?       github.com/libp2p/go-libp2p-pubsub/compat       [no test files]
?       github.com/libp2p/go-libp2p-pubsub/pb   [no test files]
2024/08/08 17:19:25 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
--- FAIL: TestGossipsubConnTagMessageDeliveries (2.52s)
    gossipsub_connmgr_test.go:158: expected most dishonest conns to be pruned, have 6
```
While running it with -count 1 works fine

**Comment by chaitanyaprem** [comment]
> Maybe it's flaky? If i run it with
> 
> ```
> go test -run TestGossipsubConnTagMessageDeliveries -count 100 --failfast ./...
> ```
> 
> I get
> 
> ```
> ?       github.com/libp2p/go-libp2p-pubsub/compat       [no test files]
> ?       github.com/libp2p/go-libp2p-pubsub/pb   [no test files]
> 2024/08/08 17:19:25 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
> --- FAIL: TestGossipsubConnTagMessageDeliveries (2.52s)
>     gossipsub_connmgr_test.go:158: expected most dishonest conns to be pruned, have 6
> ```
> 
> While running it with -count 1 works fine

Hmm, considering it flaky then and merging. Thanks!

**Pull request merged**
